<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NKE74KJ" failures="5" tests="12" name="newtestcases" time="0.167" errors="0" timestamp="2023-02-13T10:45:40 IST">
  <testcase classname="testngleaning.SumOperation" name="SubOfThree" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [1] but found [-7]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [-7]
at testngleaning.SumOperation.SubOfThree(SumOperation.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- SubOfThree -->
  <testcase classname="testngleaning.SumOperation" name="SumOfThree" time="0.002"/>
  <testcase classname="testngleaning.SumOperation" name="mulOfThree" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [9] but found [360]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [360]
at testngleaning.SumOperation.mulOfThree(SumOperation.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- mulOfThree -->
  <testcase classname="testngleaning.SumOperation" name="mulOfTwo" time="0.001"/>
  <testcase classname="testngleaning.SumOperation" name="subOfTwo" time="0.002"/>
  <testcase classname="testngleaning.SumOperation" name="sumOfTwo" time="0.001"/>
  <testcase classname="testngleaning.Arithmetic" name="addOfThree" time="0.002"/>
  <testcase classname="testngleaning.Arithmetic" name="addOfTwo" time="0.003"/>
  <testcase classname="testngleaning.Arithmetic" name="mulOfThree" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [75] but found [60]">
      <![CDATA[java.lang.AssertionError: expected [75] but found [60]
at testngleaning.Arithmetic.mulOfThree(Arithmetic.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- mulOfThree -->
  <testcase classname="testngleaning.Arithmetic" name="mulOfTwo" time="0.003"/>
  <testcase classname="testngleaning.Arithmetic" name="subOfThree" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [5] but found [-7]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [-7]
at testngleaning.Arithmetic.subOfThree(Arithmetic.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- subOfThree -->
  <testcase classname="testngleaning.Arithmetic" name="subOfTwo" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [1] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [-1]
at testngleaning.Arithmetic.subOfTwo(Arithmetic.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- subOfTwo -->
</testsuite> <!-- newtestcases -->
